<?php

namespace frontend\models;


use yii\db\ActiveRecord;

class User extends ActiveRecord
{

    public $name;

    public $login;

    public $password;

    /**
     * User constructor.
     * @param $name
     * @param $login
     * @param $password
     */
    public function __construct($params = [])
    {
        $this->name = $params['userName'];
        $this->login = $params['userLogin'];
        $this->password = $params['userPassword'];
    }

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

}